Marked tests with sanity attr
nspcc-dev/s3-tests pull request #36
Opened 2023-09-06 05:12 UTC by MaxGelbakhiani

[ Fixes nspcc-dev/neofs-s3-gw#780 ]

As a result of the review under https://github.com/nspcc-dev/neofs-s3-gw/pull/809 added sanity marks into tests

2023-09-06 10:54 UTC, vvarg229 approved these changes

2023-09-06 18:59 UTC, roman-khimov requested changes
1. No DCO
2. It doesn't fix https://github.com/nspcc-dev/neofs-s3-gw/issues/780, comment should be adjusted

2023-09-10 15:34 UTC, MaxGelbakhiani commented
> * No DCO
> * It doesn't fix [Setup GH workflows to run tests neofs-s3-gw#780](https://github.com/nspcc-dev/neofs-s3-gw/issues/780), comment should be adjusted

1. Fixed DCO.
2. Fixed commit message and PR description.

2023-09-11 06:27 UTC, roman-khimov approved these changes

2023-09-11 06:27 UTC, merged