Removed some tests from sanity list
nspcc-dev/s3-tests pull request #38
Opened 2023-09-19 18:27 UTC by MaxGelbakhiani

Adjusted sanity tests list

2023-09-19 19:03 UTC, vvarg229 requested changes

2023-09-19 19:03 UTC, vvarg229 commented on s3tests_boto3/functional/test_s3.py
> +
oops

2023-09-19 19:03 UTC, vvarg229 commented on s3tests_boto3/functional/test_s3.py
> -                ["starts-with", "$x-amz-server-side-encryption", ""],
It's not necessary

2023-09-19 19:03 UTC, vvarg229 commented on s3tests_boto3/functional/test_s3.py
> -                ["starts-with", "$x-amz-server-side-encryption", ""],
It's not necessary

2023-09-19 19:03 UTC, vvarg229 commented on s3tests_boto3/functional/test_s3.py
> -                ["starts-with", "$x-amz-server-side-encryption", ""],
It's not necessary

2023-10-05 03:23 UTC, MaxGelbakhiani commented
@vvarg229 fixed whitespaces and empty lines.

2023-10-05 08:55 UTC, vvarg229 approved these changes

2023-10-05 10:30 UTC, merged